### PR TITLE
V1.2.3

### PR DESCRIPTION
**Pull request by Ornias1993**
# Pull Request Template

### Purpose
This PR is to have a clean overview of what is going to be 1.2.3
v1.2.3 is going to be just an ordinary bug and tweak hunt. Making sure everything works as smoothly as we promise...

### Community Changelog:
- Added Code Owners
- Setup clean Issue and PR templates (replaces old templates)
- Globaly disabled SC2154 checking on PR's
- Added Security.md

### Application Changelog:
- Fixed update to use the user-set repo (make jailman fork-compatible)
- Fixed Unifi(-poller) not updating and correctly
- Fixed not exiting on failed dataset creation
- Fixed MariaDB not saving into persistence dataset
- Moved MariaDB database to /config/db (from /var/db/mysql)
- Fixed silent failure of PHPMyAdmin install
- Fixed Unifi-Poller influxdb connection
- Fixed Tautulli not starting with Python3
- add some missing nextcloud dependencies
- Move the ports installs to pkg
- Remove/Disable ports when not required
- Update all blueprints
- Remove unused dependancies
- Remove Nextcloud external database support
- Remove untested bitwarden database types

### Notes:
This update is still only tested on 11.3 and (unless hotfix is really required) will be the last on 11.3
Special thanks to @colemamd for his work on Unifi(-Poller)!

### Please make sure you have followed the self checks below before submitting a PR:

- [X] Code is sufficiently commented
- [X] Code is indented with tabs and not spaces
- [x] The PR does not bring up any new errors
- [x] The PR has been tested
- [X] Any new files are named using lowercase (to avoid issues on case sensitive file systems)

### CODE REVIEW

**Comment by Ornias1993** [comment]
@asmod3us 
I've the feeling we might want to drop 1.2.3 and go straight for a 01-07-2020 release of 1.3.0.

That way we can get the newly reworked structure in a few months before TrueNAS 12 hits and we would have enough time to do any major structural work we would like for 1.4.0 (which would release somewhere after TrueNAS 12 does)

**Comment by Ornias1993** [comment]
I would live this up till 01-07-2020 for review.
@colemamd and @asmod3us Please verify there are no new bugs and everything works as promised.

**Comment by Ornias1993** [comment]
Added the changelog

**Comment by Ornias1993** [comment]
Doing final testing as we speak...

**Comment by Ornias1993** [comment]
MariaDB install behavior was still far from consistent... trying to fix it...

**Comment by Ornias1993** [comment]
MariaDB+PHPMyAdmin from-scratch install is now fine, working and tested.

**Comment by Ornias1993** [comment]
Unifi and poller seem to install fine, database gets created

**Comment by Ornias1993** [comment]
Nextcloud needed quite a lot of work.
But is working now...

**Comment by Ornias1993** [comment]
Tautulli went to python3 which has some quircks, updated it and fixed those quircks...

**Comment by Ornias1993** [comment]
- Lidarr is working
- KMS should be working fine

**Comment by Ornias1993** [comment]
@colemamd I went over everything one more time and everything should be fully working now, could you please test Unifi and Influx one more time just to make sure?

**Comment by Ornias1993** [comment]
@thorsteneb 
You refered to wanting to do something that wouldn't cause a fuss...
This needs functionallity testing (is shit working or not), as most of it is already reworked for 1.3.0 you can ignore "that would be nice fixes"

**Comment by thorsteneb** [comment]
I can test Plex. Is traefik officially in this, or is that for 1.3.0?

**Comment by Ornias1993** [comment]
Great!
As noted in the changelog, this is just a bugfix release. So no new features are included.

**Comment by thorsteneb** [comment]
Basic Plex install and uninstall works.

I could not get beta or ramdisk to work. config.yml content and output from the script.

```
jail:
  plex:
    blueprint: plex
    ip4_addr: 192.168.3.99/24
    gateway: 192.168.3.1
    beta: true
    ramdisk: 4G
```

And script output:
```
no ramdisk specified for plex, continuing without ramdisk
Updating FreeBSD repository catalogue...
Your packages are up to date.
beta disabled in config.yml... NOT using plex beta for install
plexmediaserver_enable:  -> YES
```

**Comment by Ornias1993** [comment]
@thorsteneb Yes, indeed. 
I notice now, it some some mistakes where made because it uses the wrong syntax for variables.

I'll prepare a hotfix for it, thank you for your effort!

**Pull request merged**
