### PR TITLE
Traefik dynamic config generator

### PR DESCRIPTION
**Pull request by Ornias1993**
# Pull Request Template
### Purpose
This PR aims to implement traefik into all blueprint creation processes (on exit that is). It should keep the requirements for blueprint creators and users creating their config.yml file to a minimum

### Notes:

**There will be 3 types of config:**
1. Defaultauto-generation template (based on what you enter in the config file)
2. Custom auto-generation template (based on what you enter in the config file, but customised for a specific blueprint)
3. Fully custom config, writhen by the user

The priority goes from 3->2->1.
So if there is an fully custom user-made config available thats used, if there is a custom auto-generation template available that is being used and last (if no other is available) it is using the default template.

**Adding jails to traefik**
Adding jails to to traefik will be gosh damn easy.
It requires 3 things for the user:
- A fixed IP
- link_traefik with the name of the traefikjail
- domain_name filled with a domainname that is available using your traefik DNS provider

As we advice using fixed IP's already, for most users it just means entering a valid domain_name and link_traefik.

**Adding basic auth to jails**
Once jails are added to traefik, adding basic auth is a breeze. Space seperated, with a : between username and a hashed password, just add:
traefik_auth_basic: username1:passwordhash1 username2:passwordhash2

In the future we might automate hashing, on the other hand it might be saver NOT to use plaintext passwords when traefik already tries to prevent us from using those.

**Adding forward auth to jails**
This is even simpler than basic auth and we will supply the right config to set this up with Organizr in the readme:
traefik_auth_forward: http://urltoforward.to/auth

### Not included in this PR
- Removal of (self-signed) https from the blueprints (this will be future patches)
- Writing custom traefik templates for blueprints that need it
- Documentation, this should be done after we are sure all blueprints are either compatible or include custom config

### How to test
This PR can be tested using jails that serve a "simple" website over http.
Example:
- jackett
- radarr
- sonarr
- lidarr

A full round of compatibility testing an patching is (as stated in the "not included" section) to-be-done in a future PR.

### Please make sure you have followed the self checks below before submitting a PR:

- [X] Code is sufficiently commented
- [X] Code is indented with tabs and not spaces
- [X] The PR does not bring up any new errors
- [X] The PR has been tested
- [X] Any new files are named using lowercase (to avoid issues on case sensitive file systems)

### CODE REVIEW

**Comment by Ornias1993** [comment]
Current version has working non-auth and forward-auth for jails.
Basic-auth is tbd.

**Comment by Ornias1993** [comment]
Fully tested, ready for review.
Will be merged in 24 hours.

**Comment by asmod3us** [comment]
I'm testing this and noticed an extra space is generated at the end of DOMAIN:

```
        [http.routers.traefik.tls]
          certResolver = "default" # From static configuration
          [[http.routers.traefik.tls.domains]]
            main = "MY.DOMAIN "
            sans = ["*.MY.DOMAIN "]
```

**Comment by Ornias1993** [comment]
@asmod3us You sure there is no extra space in your config file?

The codepath for this doesn't add any spaces...
```
else
	echo "wildcard set, enabling wildcard config..."
	iocage exec "${1}" sed -i '' "s|placeholderwildcard|${cert_wildcard_domain}|" /config/dynamic/dashboard.toml
fi
```
and 
```
          [[http.routers.traefik.tls.domains]]
            main = "placeholderwildcard"
            sans = ["*.placeholderwildcard"]
```

**Comment by asmod3us** [comment]
indeed, thanks! vim over ssh not showing spaces in my config...

**Comment by Ornias1993** [comment]
@asmod3us To give you an idea, this is my test traefik config:

```
  traefikjail:
    blueprint: traefik
    ip4_addr: 192.168.20.243/24
    gateway: 192.168.20.1
    dashboard: true
    cert_staging: true
    domain_name: traefik.test.schouten-lebbing.nl
    cert_email: kjeld@schouten-lebbing.nl
    dns_provider: cloudflare
    cert_wildcard_domain: test.schouten-lebbing.nl
    # Please follow the guide here: https://docs.traefik.io/https/acme/
    # and enter your DNS providers environment variables below (2 spaces indent) of cert_env
    cert_env:
      CF_API_EMAIL: yeah@no.seriesuly.not
      CF_API_KEY: 4TqwEPDPfNFjjXe6tpwiCpTA
```

Jackett behind traefik, without auth:
```
  jackettjail:
    blueprint: jackett
    domain_name: jackett.test.schouten-lebbing.nl
    link_traefik: traefikjail
    ip4_addr: 192.168.20.218/24
    gateway: 192.168.20.1
```

Sonarr with forward auth to an organizr server:
```
  sonarrjail:
    blueprint: sonarr
    domain_name: sonarr.test.schouten-lebbing.nl
    link_traefik: traefikjail
    traefik_auth_forward: https://organizr.test.schouten-lebbing.nl/api/?v1/auth&group=1
    ip4_addr: 192.168.20.215/24
    gateway: 192.168.20.1
```

radarr with basic auth (user1:pass1 user2:pass2):
```
  radarrjail:
    blueprint: radarr
    domain_name: radarr.test.schouten-lebbing.nl
    link_traefik: traefikjail
    traefik_auth_basic: user1:$2a$13$rrZwSV4sDJ7G/1dEO0vsiulh/2YG/j7fdc910C/1ikdmR4L7rCJ7i user2:user2:$2a$13$t7KA/CaS88S1jrGRdeOIqeq8XIn4m3RB.oeEsbmlUB4FcT5S9Qg0a
    ip4_addr: 192.168.20.216/24
    gateway: 192.168.20.1
```
Nice tool (in dutch sadly enough) to generate the hased user:password string:
https://www.transip.nl/htpasswd/

**Comment by asmod3us** [comment]
Thanks for sharing your config. Is the dashboard reachable from within the jail via curl?
Im struggling to reach the dashboard from inside the jail (or outside):

```
root@traefik:/config # curl -vk https://localhost:9443/dashboard/
*   Trying ::1:9443...
* Connected to localhost (::1) port 9443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/share/certs/ca-root-nss.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=TRAEFIK DEFAULT CERT
*  start date: May 31 17:50:23 2020 GMT
*  expire date: May 31 17:50:23 2021 GMT
*  issuer: CN=TRAEFIK DEFAULT CERT
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x803ad7800)
> GET /dashboard/ HTTP/2
> Host: localhost:9443
> user-agent: curl/7.69.1
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 404
< content-type: text/plain; charset=utf-8
< x-content-type-options: nosniff
< content-length: 19
< date: Sun, 31 May 2020 17:54:41 GMT
<
404 page not found
```

Same result when using the local ip address of the jail and/or with IPv4 (`curl -4`). What am I missing? Traefik access log shows the 404s.

**Comment by Ornias1993** [comment]
@asmod3us Thats what we call "User Error" ;)
GTFM.

https://github.com/jailmanager/jailman/pull/149/files#diff-1c023540639fd8932b50c410fa4346a5

**Comment by Ornias1993** [comment]
Shoot, just reread my code, It should be available using a temporary hack I added, but isn't... just removing the hack and requiring a DNS name

**Comment by Ornias1993** [comment]
Oops wrong button...

**Comment by asmod3us** [comment]
As for port 9080/9443, we should change the docs to state the dashboard is *only* 80 and 443 on the host you've configured. traefik only provides a 404 on 9080/9443 with the shipped config.

I think I found the deeper issue. In my case it's a caching dns resolver that did not deliver cloudflare dns updates to the client right away. I'm just saying we need a troubleshooting section to point out what issues we're not providing support for ;-)

So I think what helps to troubleshoot traefik on my.domain configured with hosttraefik.my.domain:

Output of commands:
```
host traefik.my.domain
```

You want this to point to the ip of the jail.

```
dig @1.1.1.1 traefik.my.domain
```
Should return the ip of the traefik jail

```
grep 'traefik.my.domain' /etc/hosts
```

should either return nothing or point that host to the ip of the jail.

WDYT?

**Comment by Ornias1993** [comment]
> In my case it's a caching dns resolver that did not deliver cloudflare dns updates to the client right away. I'm just saying we need a troubleshooting section to point out what issues we're not providing support for ;-)

Actually there is a fix for that... will send it in soon (you can override the default DNS server for traefik DNS auth)

**Comment by Ornias1993** [comment]
NVM, Traefik doesn't setup cloudflare so your client can connect.
It only verifies your Domain ownership using cloudflare.

**Comment by asmod3us** [comment]
Yeah not the TXT records for validation but the a cached answer to the modified dns entries I set for traefik.

**Comment by Ornias1993** [comment]
> Yeah not the TXT records for validation but the a cached answer to the modified dns entries I set for traefik.

Yeah thats not something within the scope...
Thats not actually something for us to document. Thats an upstream issue or support request..

**Comment by Ornias1993** [comment]
Anyhow @asmod3us did you manage to test it? :)

**Comment by asmod3us** [comment]
Working on connecting a jail to traffic now...

**Comment by asmod3us** [comment]
Don't mind me, I'm stupid, I was on the wrong git branch on the nas system the whole time 🤦

**Comment by Ornias1993** [comment]
I'm merging this...
Didn't get any feedback, but we can get back to it with the last itteration of the Traefik patches, which includes documentation and migrating all jails

**Pull request merged**
